---
name: Spotify Connect (unofficial, latest librespot)
version: 0.11.0-marcodaum
slug: spotify
description: Play Spotify music on your Home Assistant device
url: https://github.com/hassio-addons/addon-spotify-connect
arch:
  - aarch64
  - amd64
  - armv7
  - i386
homeassistant_api: true
host_network: true
audio: true
options:
  name: Home Assistant
  bitrate: 320
  initial_volume: 100
  volume_scaling: log
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  initial_volume: int(0,100)
  volume_scaling: list(linear|log|fixed)
  create_entity: bool?
  username: str?
  password: password?
